const palette = {
  sage: '#8FB996',
  mint: '#A8D5BA',
  lavender: '#B8A9C9',
  softPeach: '#F5D6C6',
  warmCream: '#FFF8F0',
  deepTeal: '#2D6A6A',
  mutedBlue: '#7BA7BC',
  coral: '#E8927C',
  darkSlate: '#2C3E50',
  charcoal: '#3D4F5F',
  lightGray: '#F0F4F3',
  white: '#FFFFFF',
  gemGold: '#E8B84B',
  gemShimmer: '#F4D68C',
  softRed: '#E88B8B',
  softGreen: '#8BC9A3',
  softYellow: '#F4D68C',
  softBlue: '#8BB8E8',
  softPurple: '#B8A9C9',
};

export default {
  light: {
    text: palette.darkSlate,
    textSecondary: palette.charcoal,
    background: palette.warmCream,
    card: palette.white,
    tint: palette.deepTeal,
    tabIconDefault: palette.mutedBlue,
    tabIconSelected: palette.deepTeal,
    accent: palette.sage,
    accentSecondary: palette.lavender,
    peach: palette.softPeach,
    gem: palette.gemGold,
    gemShimmer: palette.gemShimmer,
    border: '#E8E4DF',
    overlay: 'rgba(44, 62, 80, 0.08)',
    success: palette.softGreen,
    warning: palette.softYellow,
    danger: palette.softRed,
    calm: palette.softBlue,
    mindful: palette.softPurple,
  },
  palette,
};
